config/routes.rb
Rails.application.routes.draw do
  resources :devizes do
      resources :valutes
  end
  get 'test/', to: 'valutes#hnbApi'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/devize.rb
class Devize
  include Mongoid::Document
  include Mongoid::Alize

  field :datum, type: DateTime
  field :kupovni, type: String
  field :srednji, type: String
  field :prodajni, type: String


  # belongs_to :devize_valute, :class => 'Valute', :inverse_of => :valute_devize
  belongs_to :valute, :class_name => 'Valute', :inverse_of => :devize
  # ***
  alize :valute
  # ***
end

app/models/valute.rb
class Valute
  include Mongoid::Document
  include Mongoid::Alize

  field :valuta, type: String
  field :drzava, type: String
  field :sifraValute, type: Integer
  field :jedinica, type: Integer

  # has_many :valute_devize
  has_many :devize, :class_name => 'Devize', :inverse_of => :valute

  # ***
  alize :devize
  # ***
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/hnbApiService.rb
require 'net/http'
require 'json'
require 'active_support'
require 'active_support/core_ext'

class HnbApiService
  @@api = 'http://api.hnb.hr/tecajn/v1'

  def update()

    @tecajnaLista = getTecaj() #array objekata

    @tecajnaLista.each do |tecaj|
      @valute = Valute.new({
        valuta: tecaj["Valuta"],
        drzava: tecaj["Država"],
        sifraValute: tecaj["Šifra valute"],
        jedinica: tecaj["Jedinica"]
      })

      @valute.devize(Devize.create!({
        datum: tecaj["Datum primjene"],
        kupovni: tecaj["Kupovni za devize"],
        srednji: tecaj["Srednji za devize"],
        prodajni: tecaj["Prodajni za devize"]
      }))
      pp @valute
      @valute.save

    end
    
    return @valute
  end

  def getTecaj()
    uri = URI(@@api)
    response = Net::HTTP.get(uri)
    response = JSON.parse(response)
    return response
  end

end

app/controllers/devizes_controller.rb
class DevizesController < ApplicationController
  before_action :set_devize, only: [:show, :edit, :update, :destroy]

  # GET /devizes
  # GET /devizes.json
  def index
    @devizes = Devize.all
  end

  # GET /devizes/1
  # GET /devizes/1.json
  def show
  end

  # GET /devizes/new
  def new
    @devize = Devize.new
  end

  # GET /devizes/1/edit
  def edit
  end

  # POST /devizes
  # POST /devizes.json
  def create
    @devize = Devize.new(devize_params)

    respond_to do |format|
      if @devize.save
        format.html { redirect_to @devize, notice: 'Devize was successfully created.' }
        format.json { render :show, status: :created, location: @devize }
      else
        format.html { render :new }
        format.json { render json: @devize.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devizes/1
  # PATCH/PUT /devizes/1.json
  def update
    respond_to do |format|
      if @devize.update(devize_params)
        format.html { redirect_to @devize, notice: 'Devize was successfully updated.' }
        format.json { render :show, status: :ok, location: @devize }
      else
        format.html { render :edit }
        format.json { render json: @devize.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devizes/1
  # DELETE /devizes/1.json
  def destroy
    @devize.destroy
    respond_to do |format|
      format.html { redirect_to devizes_url, notice: 'Devize was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_devize
      @devize = Devize.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def devize_params
      params.require(:devize).permit(:valute_id)
    end
end

app/controllers/valutes_controller.rb
require_relative 'concerns/hnbApiService.rb'

class ValutesController < ApplicationController
  before_action :set_valute, only: [:show, :edit, :update, :destroy]

    
  def hnbApi
    @hnbApiService = HnbApiService.new
    render json: @hnbApiService.update
  end 

  # GET /valutes
  # GET /valutes.json
  def index
    @valutes = Valute.all
  end

  # GET /valutes/1
  # GET /valutes/1.json
  def show
  end

  # GET /valutes/new
  def new
    @valute = Valute.new
  end

  # GET /valutes/1/edit
  def edit
  end

  # POST /valutes
  # POST /valutes.json
  def create
    @valute = Valute.new(valute_params)

    respond_to do |format|
      if @valute.save
        format.html { redirect_to @valute, notice: 'Valute was successfully created.' }
        format.json { render :show, status: :created, location: @valute }
      else
        format.html { render :new }
        format.json { render json: @valute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valutes/1
  # PATCH/PUT /valutes/1.json
  def update
    respond_to do |format|
      if @valute.update(valute_params)
        format.html { redirect_to @valute, notice: 'Valute was successfully updated.' }
        format.json { render :show, status: :ok, location: @valute }
      else
        format.html { render :edit }
        format.json { render json: @valute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valutes/1
  # DELETE /valutes/1.json
  def destroy
    @valute.destroy
    respond_to do |format|
      format.html { redirect_to valutes_url, notice: 'Valute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valute
      @valute = Valute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valute_params
      params.fetch(:valute, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devizes_helper.rb
module DevizesHelper
end

app/helpers/valutes_helper.rb
module ValutesHelper
end

app/views/devizes/_form.html.erb
<%= form_with(model: devize, local: true) do |form| %>
  <% if devize.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(devize.errors.count, "error") %> prohibited this devize from being saved:</h2>

      <ul>
      <% devize.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :valute_id %>
    <%= form.text_field :valute_id, id: :devize_valute_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devizes/edit.html.erb
<h1>Editing Devize</h1>

<%= render 'form', devize: @devize %>

<%= link_to 'Show', @devize %> |
<%= link_to 'Back', devizes_path %>

app/views/devizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devizes</h1>

<table>
  <thead>
    <tr>
      <th>Valute</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devizes.each do |devize| %>
      <tr>
        <td><%= devize.valute %></td>
        <td><%= link_to 'Show', devize %></td>
        <td><%= link_to 'Edit', edit_devize_path(devize) %></td>
        <td><%= link_to 'Destroy', devize, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Devize', new_devize_path %>

app/views/devizes/new.html.erb
<h1>New Devize</h1>

<%= render 'form', devize: @devize %>

<%= link_to 'Back', devizes_path %>

app/views/devizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Valute:</strong>
  <%= @devize.valute %>
</p>

<%= link_to 'Edit', edit_devize_path(@devize) %> |
<%= link_to 'Back', devizes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestAlize</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/valutes/_form.html.erb
<%= form_with(model: valute, local: true) do |form| %>
  <% if valute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valute.errors.count, "error") %> prohibited this valute from being saved:</h2>

      <ul>
      <% valute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/valutes/edit.html.erb
<h1>Editing Valute</h1>

<%= render 'form', valute: @valute %>

<%= link_to 'Show', @valute %> |
<%= link_to 'Back', valutes_path %>

app/views/valutes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Valutes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @valutes.each do |valute| %>
      <tr>
        <td><%= link_to 'Show', valute %></td>
        <td><%= link_to 'Edit', edit_valute_path(valute) %></td>
        <td><%= link_to 'Destroy', valute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Valute', new_valute_path %>

app/views/valutes/new.html.erb
<h1>New Valute</h1>

<%= render 'form', valute: @valute %>

<%= link_to 'Back', valutes_path %>

app/views/valutes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_valute_path(@valute) %> |
<%= link_to 'Back', valutes_path %>